#include "test.h"

int main() {
    int a;
    int b;
    int c;
    int d;
    int e;
    int f;
    int g;
    int h;
    int i;
    int j;
    int k;
    int l;
    int m;
    int n;
    int o;
    int p;
    int q;
    int r;
    int s;
    int t;
    int u;
    int v;
    int w;
    int x;
    int y;
    int z;

    a = 10;
    ASSERT(9, a - 1);
    b = -14;
    ASSERT(2, b + 16);
    c = -6;
    ASSERT(24, c * (-4));
    d = (3 < 5);
    ASSERT(3, d + 2);
    e = -134;
    ASSERT(4, e + 138);
    f = (10 - 5 * 3);
    ASSERT(15, f + 20);
    g = 1;
    h = 1;
    i = 12;
    j = -15;
    ASSERT(17, i + 5);
    k = 1;
    l = 1;
    m = 12;
    n = -15;
    ASSERT(4, n + 19);
    o = 16 / 1;
    p = (1 - 3) * 8;
    q = 12;
    r = -15;
    ASSERT(21, o + 5);
    s = 1;
    t = 1;
    u = (10 - 3) * 3 * 2;
    v = -15;
    ASSERT(6, u / 7);
    u = 1;
    v = 1;
    w = 12;
    ASSERT(3, w - 9);
    x = 1;
    y = 1;
    z = 12;
    ASSERT(9, x + 8);
    a = 26;
    b = a - 46;
    c = b / 2;
    ASSERT(20, c + 30);
    d = -2;
    e = d * 45;
    f = e * 3;
    g = f + e;
    h = g + d;
    ASSERT(0, h + 362);
    x = 2;
    y = x + 3;
    z = y * 2;
    ASSERT(8, z - 2);
    int hoge;
    int fuga;
    hoge = 3;
    fuga = hoge * 3;
    ASSERT(7, fuga - 2);
    int abc;
    int ABC;
    int CC;
    abc = 398;
    ABC = -352;
    CC  = abc + ABC;
    ASSERT(12, CC - 34);
    int pwoef;
    int goiao;
    int garhi;
    pwoef = 34;
    goiao = -354 + pwoef;
    garhi = goiao / 32;
    ASSERT(10, garhi + 20);
    int ieii;
    int g_1e;
    int A;
    ieii = 143;
    g_1e = -43;
    A    = ieii + g_1e;
    ASSERT(100, A);
    ok();
    return 0;
}